#!/usr/bin/env python3
"""Build floorplan.svg from a list of measured segments. Scale: 4 px = 1 inch, north up."""
from pathlib import Path

SCALE = 4  # px per inch
START = ("A", 0, 0)  # label, x inches (east +), y inches (south +)
DIRS = {"N": (0, -1), "S": (0, 1), "E": (1, 0), "W": (-1, 0)}

# (direction, length in inches, kind, end label[, start label])
# Start label defaults to the previous segment's end point.
SEGMENTS = [
    ("S", 46, "wall", "B"),
    ("S", 42, "window", "C"),
    ("S", 48, "wall", "D"),
    ("S", 42, "window", "E"),
    ("S", 48, "wall", "F"),
    ("S", 42, "window", "G"),
    ("S", 48, "wall", "H"),
    ("W", 46, "wall", "I"),
    ("W", 24, "wall", "J"),
    ("W", 24, "wall", "K"),
    ("W", 30, "wall", "L"),
    ("W", 40, "wall", "M"),
    ("N", 60, "wall", "N"),
    ("E", 40, "wall", "N1"),
    ("N", 41, "wall", "O", "N"),
    ("N", 48, "wall", "P"),
    ("N", 30, "wall", "Q"),
    ("N", 96, "opening", "R"),
    ("N", 36, "wall", "S"),
    ("E", 23, "wall", "T"),
    ("E", 32, "door:laundry door", "U"),  # hinged at T, swings north into the laundry
    ("E", 61, "wall", "V"),
    ("E", 36, "door", "W"),  # swings open inside
    ("E", 10, "wall", "X"),
]

LABELS = {"opening": "walkway opening"}
MARGIN = 80
# Overall run dimensions drawn outside the segment dimensions: (from label, to label)
TOTALS = [("D", "H"), ("H", "L")]

DIM_OFFSET = 40  # px, dimension line offset to the left/top of the segment


def build():
    pts = [START]
    by_label = {START[0]: START}
    starts = []
    for seg in SEGMENTS:
        d, length, _, label = seg[:4]
        start = by_label[seg[4]] if len(seg) > 4 else pts[-1]
        starts.append(start)
        dx, dy = DIRS[d]
        pt = (label, start[1] + dx * length, start[2] + dy * length)
        pts.append(pt)
        by_label[label] = pt

    xs = [p[1] for p in pts]
    ys = [p[2] for p in pts]
    ox = MARGIN + 80 - min(xs) * SCALE
    oy = MARGIN - min(ys) * SCALE
    width = int((max(xs) - min(xs)) * SCALE + 2 * MARGIN + 240)
    height = int((max(ys) - min(ys)) * SCALE + 2 * MARGIN + 60)

    def P(px, py):
        return ox + px * SCALE, oy + py * SCALE

    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by build_floorplan.py. Scale: 4 px = 1 inch. North is up. -->",
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}" font-family="Helvetica, Arial, sans-serif">',
        f'  <rect width="{width}" height="{height}" fill="#ffffff"/>',
        f'  <g id="north" transform="translate({width - 40},40)"><circle r="14" fill="none" stroke="#555"/>'
        '<path d="M 0 -11 L 5 7 L 0 3 L -5 7 Z" fill="#333"/><text y="-18" font-size="10" fill="#555" text-anchor="middle">N</text></g>',
    ]

    for i, seg in enumerate(SEGMENTS):
        d, length, kind, label = seg[:4]
        kind, _, name = kind.partition(":")
        name = name or LABELS.get(kind, kind)
        a, b = starts[i], pts[i + 1]
        x1, y1 = P(a[1], a[2])
        x2, y2 = P(b[1], b[2])
        vertical = d in "NS"
        seg_id = f"{kind}-{a[0]}{b[0]}"
        if kind == "wall":
            out.append(f'  <line id="{seg_id}" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#2b2b2b" stroke-width="8"/>')
        elif kind == "door":
            # Door shown as a gap with jambs (no swing drawn).
            jx, jy = (6, 0) if vertical else (0, 6)
            out.append(f'  <g id="{seg_id}" stroke="#2b2b2b"><line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#8a6a3d" stroke-width="2"/>'
                       f'<line x1="{x1-jx}" y1="{y1-jy}" x2="{x1+jx}" y2="{y1+jy}" stroke-width="3"/>'
                       f'<line x1="{x2-jx}" y1="{y2-jy}" x2="{x2+jx}" y2="{y2+jy}" stroke-width="3"/></g>')
        elif kind == "opening":
            jx, jy = (6, 0) if vertical else (0, 6)
            out.append(f'  <g id="{seg_id}" stroke="#2b2b2b"><line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#999" stroke-dasharray="6 5"/>'
                       f'<line x1="{x1-jx}" y1="{y1-jy}" x2="{x1+jx}" y2="{y1+jy}" stroke-width="3"/>'
                       f'<line x1="{x2-jx}" y1="{y2-jy}" x2="{x2+jx}" y2="{y2+jy}" stroke-width="3"/></g>')
        else:
            rx, ry = min(x1, x2) - (4 if vertical else 0), min(y1, y2) - (0 if vertical else 4)
            rw, rh = (8, abs(y2 - y1)) if vertical else (abs(x2 - x1), 8)
            out.append(f'  <g id="{seg_id}"><rect x="{rx}" y="{ry}" width="{rw}" height="{rh}" fill="#fff" stroke="#2b2b2b"/>'
                       f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#4a6b80" stroke-width="2"/></g>')
        # dimension
        if vertical:
            side = 1 if (x1 - ox) / SCALE >= (min(xs) + max(xs)) / 2 else -1  # keep dims outside the room
            dx_ = x1 + side * (DIM_OFFSET + 30)
            mid = (y1 + y2) / 2
            out.append(f'  <g stroke="#888"><line x1="{dx_}" y1="{y1}" x2="{dx_}" y2="{y2}"/>'
                       f'<line x1="{dx_-6}" y1="{y1}" x2="{dx_+6}" y2="{y1}"/><line x1="{dx_-6}" y1="{y2}" x2="{dx_+6}" y2="{y2}"/></g>')
            out.append(f'  <text x="{dx_+16*side}" y="{mid}" font-size="12" fill="#444" text-anchor="middle" transform="rotate({90*side} {dx_+16*side} {mid})">{length}" {name}</text>')
        else:
            vside = 1 if (y1 - oy) / SCALE >= (min(ys) + max(ys)) / 2 else -1
            dy_ = y1 + vside * DIM_OFFSET
            mid = (x1 + x2) / 2
            out.append(f'  <g stroke="#888"><line x1="{x1}" y1="{dy_}" x2="{x2}" y2="{dy_}"/>'
                       f'<line x1="{x1}" y1="{dy_-6}" x2="{x1}" y2="{dy_+6}"/><line x1="{x2}" y1="{dy_-6}" x2="{x2}" y2="{dy_+6}"/></g>')
            out.append(f'  <text x="{mid}" y="{dy_+(16 if vside > 0 else -8)}" font-size="12" fill="#444" text-anchor="middle">{length}" {name}</text>')

    for a_lbl, b_lbl in TOTALS:
        a, b = by_label[a_lbl], by_label[b_lbl]
        x1, y1 = P(a[1], a[2])
        x2, y2 = P(b[1], b[2])
        inches = abs(b[1] - a[1]) + abs(b[2] - a[2])
        ft, rem = divmod(inches, 12)
        text = f"{a_lbl}–{b_lbl}: {f"{inches / 12:.2f}".rstrip("0").rstrip(".")} linear ft ({ft}′-{rem}″)"
        if x1 == x2:
            side = 1 if (x1 - ox) / SCALE >= (min(xs) + max(xs)) / 2 else -1
            dx_ = x1 + side * (DIM_OFFSET + 90)
            mid = (y1 + y2) / 2
            out.append(f'  <g stroke="#c0392b"><line x1="{dx_}" y1="{y1}" x2="{dx_}" y2="{y2}"/>'
                       f'<line x1="{dx_-8}" y1="{y1}" x2="{dx_+8}" y2="{y1}"/><line x1="{dx_-8}" y1="{y2}" x2="{dx_+8}" y2="{y2}"/></g>')
            out.append(f'  <text x="{dx_+18*side}" y="{mid}" font-size="13" font-weight="700" fill="#c0392b" text-anchor="middle" transform="rotate({90*side} {dx_+18*side} {mid})">{text}</text>')
        else:
            vside = 1 if (y1 - oy) / SCALE >= (min(ys) + max(ys)) / 2 else -1
            dy_ = y1 + vside * (DIM_OFFSET + 50)
            mid = (x1 + x2) / 2
            out.append(f'  <g stroke="#c0392b"><line x1="{x1}" y1="{dy_}" x2="{x2}" y2="{dy_}"/>'
                       f'<line x1="{x1}" y1="{dy_-8}" x2="{x1}" y2="{dy_+8}"/><line x1="{x2}" y1="{dy_-8}" x2="{x2}" y2="{dy_+8}"/></g>')
            out.append(f'  <text x="{mid}" y="{dy_+(18 if vside > 0 else -8)}" font-size="13" font-weight="700" fill="#c0392b" text-anchor="middle">{text}</text>')

    out.append('  <g font-size="14" font-weight="700" fill="#c0392b">')
    for label, px, py in pts:
        cx, cy = P(px, py)
        out.append(f'    <circle cx="{cx}" cy="{cy}" r="5"/><text x="{cx + 10}" y="{cy - 10}">{label}</text>')
    out.append("  </g>")
    out.append("</svg>")
    Path(__file__).with_name("floorplan.svg").write_text("\n".join(out) + "\n")
    return width, height


if __name__ == "__main__":
    print(*build())
